<?xml version="1.0" encoding="UTF-8"?><testrun name="TestMatrixPublic" project="AI" tests="1" started="1" failures="1" errors="0" ignored="0">
  <testsuite name="tests.TestMatrixPublic" time="0.043" displayname="TestMatrixPublic" uniqueid="[engine:junit-vintage]/[runner:tests.TestMatrixPublic]">
    <testcase name="testa1" classname="tests.TestMatrixPublic" time="0.043" displayname="testa1" uniqueid="[engine:junit-vintage]/[runner:tests.TestMatrixPublic]/[test:testa1(tests.TestMatrixPublic)]">
      <failure>java.lang.AssertionError: The output actions do not lead to a goal state.&#13;
	at org.junit.Assert.fail(Assert.java:89)&#13;
	at org.junit.Assert.assertTrue(Assert.java:42)&#13;
	at tests.TestMatrixPublic.testa1(TestMatrixPublic.java:45)&#13;
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)&#13;
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)&#13;
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)&#13;
	at java.base/java.lang.Thread.run(Thread.java:831)&#13;
&#13;
</failure>
    </testcase>
  </testsuite>
</testrun>
